### PR TITLE
Unpack the `tar.gz`

### PR DESCRIPTION
**Pull request by bewt85**
Hi Nick,

What do you think about having the files uncompressed in the repo.  The advantage is that if you add or remove alleles, it'll be much easier to diff the differences.

A tar.gz and zip are created automatically [when you make a release](https://github.com/bewt85/pneumo-cgmlst/releases) so it should still be compatible with the software we've been testing.

I'll delete my fork if you merge / reject this so that we avoid confusion about who made the scheme.

All the best, Ben

### CODE REVIEW

**Comment by nickjcroucher** [comment]
Hi Ben,

This is just rolling back the update Ben0 requested, if this works better for you happy to accommodate the change.

Cheers,

Nick.

**Comment by bewt85** [comment]
Thanks Nick.  Do you mind making a 1.0.0 Release?

Thanks,

Ben

**Comment by nickjcroucher** [comment]
Done!

**Comment by bewt85** [comment]
Thanks 😃

**Pull request merged**
